--
-- PostgreSQL database dump
--

SET client_encoding = 'SQL_ASCII';
SET check_function_bodies = false;

SET SESSION AUTHORIZATION 'narendra';

SET search_path = public, pg_catalog;

--
-- TOC entry 3 (OID 90832)
-- Name: i_qtr_def; Type: TABLE; Schema: public; Owner: narendra
--

CREATE TABLE i_qtr_def (
    qtr_num smallint,
    qtr_desc character varying
);


--
-- Data for TOC entry 4 (OID 90832)
-- Name: i_qtr_def; Type: TABLE DATA; Schema: public; Owner: narendra
--

INSERT INTO i_qtr_def VALUES (1, '01-April-2005:30-June-2005');
INSERT INTO i_qtr_def VALUES (3, '01-July-2005:30-September-2005');
INSERT INTO i_qtr_def VALUES (4, '01-October-2005:31-December-2005');
INSERT INTO i_qtr_def VALUES (1, '01-January-2006:31-March-2006');
INSERT INTO i_qtr_def VALUES (2, '01-April-2006:30-June-2006');
INSERT INTO i_qtr_def VALUES (3, '01-July-2006:30-September-2006');
INSERT INTO i_qtr_def VALUES (4, '01-October-2006:31-December-2006');
INSERT INTO i_qtr_def VALUES (1, '01-January-2007:31-Mar-2007');
INSERT INTO i_qtr_def VALUES (2, '01-April-2007:30-June-2007');
INSERT INTO i_qtr_def VALUES (3, '01-July-2007:30-September-2007');
INSERT INTO i_qtr_def VALUES (4, '01-October-2007:31-December-2007');


